## Part 1: Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
import pandas as pd
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras import layers

#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

Age Attrition     BusinessTravel              Department  DistanceFromHome  \
0   41       Yes      Travel_Rarely                   Sales                 1   
1   49        No  Travel_Frequently  Research & Development                 8   
2   37       Yes      Travel_Rarely  Research & Development                 2   
3   33        No  Travel_Frequently  Research & Development                 3   
4   27        No      Travel_Rarely  Research & Development                 2   

   Education EducationField  EnvironmentSatisfaction  HourlyRate  \
0          2  Life Sciences                        2          94   
1          1  Life Sciences                        3          61   
2          2          Other                        4          92   
3          4  Life Sciences                        4          56   
4          1        Medical                        1          40   

   JobInvolvement  ...  PerformanceRating RelationshipSatisfaction  \
0               3  ...                  3                        1   
1               2  ...                  4                        4   
2               2  ...                  3                        2   
3               3  ...                  3                        3   
4               3  ...                  3                        4   

   StockOptionLevel TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  \
0                 0                 8                      0               1   
1                 1                10                      3               3   
2                 0                 7                      3               3   
3                 0                 8                      3               3   
4                 1                 6                      3               3   

   YearsAtCompany  YearsInCurrentRole  YearsSinceLastPromotion  \
0               6                   4                        0   
1              10                   7                        1   
2               0                   0                        0   
3               8                   7                        3   
4               2                   2                        2   

   YearsWithCurrManager  
0                     5  
1                     7  
2                     0  
3                     0  
4                     2  

[5 rows x 27 columns]

In [2]:
# Determine the number of unique values in each column.
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [3]:
# Create y_df with the Attrition and Department columns
y_df = attrition_df[['Attrition', 'Department']]
y_df.head()


Attrition              Department
0       Yes                   Sales
1        No  Research & Development
2       Yes  Research & Development
3        No  Research & Development
4        No  Research & Development

In [4]:
y_df['Department'].value_counts()

Department
Research & Development    961
Sales                     446
Human Resources            63
Name: count, dtype: int64

In [5]:
y_df['Attrition'].value_counts()

Attrition
No     1233
Yes     237
Name: count, dtype: int64

In [6]:
# Create a list of at least 10 column names to use as X data
X_list = [
    'Education',
    'Age',
    'DistanceFromHome',
    'JobSatisfaction',
    'OverTime',
    'StockOptionLevel',
    'WorkLifeBalance',
    'YearsAtCompany',
    'YearsSinceLastPromotion',
    'NumCompaniesWorked',
    ]


# Create X_df using your selected columns
X_df = attrition_df[X_list].copy()

# Show the data types for X_df
X_df.dtypes


Education                   int64
Age                         int64
DistanceFromHome            int64
JobSatisfaction             int64
OverTime                   object
StockOptionLevel            int64
WorkLifeBalance             int64
YearsAtCompany              int64
YearsSinceLastPromotion     int64
NumCompaniesWorked          int64
dtype: object

In [7]:
X_df['OverTime'].value_counts()

OverTime
No     1054
Yes     416
Name: count, dtype: int64

In [8]:
# Convert your X data to numeric data types however you see fit
# Add new code cells as necessary
le = LabelEncoder()
X_df['OverTime'] = le.fit_transform(X_df['OverTime'])
X_df.head()

Education  Age  DistanceFromHome  JobSatisfaction  OverTime  \
0          2   41                 1                4         1   
1          1   49                 8                2         0   
2          2   37                 2                3         1   
3          4   33                 3                3         1   
4          1   27                 2                2         0   

   StockOptionLevel  WorkLifeBalance  YearsAtCompany  YearsSinceLastPromotion  \
0                 0                1               6                        0   
1                 1                3              10                        1   
2                 0                3               0                        0   
3                 0                3               8                        3   
4                 1                3               2                        2   

   NumCompaniesWorked  
0                   8  
1                   1  
2                   6  
3                   1  
4                   9

In [9]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_df, y_df, random_state=13)


In [10]:
# Create a StandardScaler
scaler = StandardScaler()

# Fit the StandardScaler to the training data
scaler.fit(X_train)

# Scale the training and testing data
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)


In [11]:
# Create a OneHotEncoder for the Department column
ohe = OneHotEncoder(sparse_output=False, drop=None, handle_unknown='ignore')

# Fit the encoder to the training data
y_train_department = ohe.fit_transform(y_train[['Department']])
y_test_department = ohe.transform(y_test[['Department']])

# Create two new variables by applying the encoder
# to the training and testing data
print(y_train_department[:5])
print(y_test_department[:5])


[[0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]]
[[0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
# Create a OneHotEncoder for the Attrition column
ohe_attrition = OneHotEncoder(sparse_output=False, drop=None, handle_unknown='ignore')

# Fit the encoder to the training data
y_train_attrition = ohe_attrition.fit_transform(y_train[['Attrition']])
y_test_attrition = ohe_attrition.transform(y_test[['Attrition']])

# Create two new variables by applying the encoder
# to the training and testing data
print(y_train_attrition[:5])
print(y_test_attrition[:5])


[[1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]]
[[1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]]


## Create, Compile, and Train the Model

In [45]:
from tensorflow.keras.regularizers import l2

# Find the number of columns in the X training data
input_features = X_train_scaled.shape[1]

# Create the input layer
input_layer = layers.Input(shape=(input_features,))

# Create at least two shared layers
shared_layer1 = layers.Dense(units=64, activation='tanh', kernel_regularizer=l2(0.01))(input_layer)
shared_layer2 = layers.Dense(units=64, activation='relu', kernel_regularizer=l2(0.01))(shared_layer1)

In [46]:
# Create a branch for Department
# with a hidden layer and an output layer
# Create the hidden layer
hidden_layer_department = layers.Dense(units=64, activation='relu', name='hidden_layer_department')(shared_layer2)

# Create the output layer
output_layer_department = layers.Dense(y_train_department.shape[1], activation='softmax', name='output_layer_department')(hidden_layer_department)


In [47]:
# Create a branch for Attrition
# with a hidden layer and an output layer

# Create the hidden layer
hidden_layer_attrition = layers.Dense(units=64, activation='relu', name='hidden_layer_attrition')(shared_layer2)

# Create the output layer
output_layer_attrition = layers.Dense(y_train_attrition.shape[1], activation='sigmoid', name='output_layer_attrition')(hidden_layer_attrition)


In [48]:
# Create the model
model = Model(inputs=input_layer, outputs=[output_layer_department, output_layer_attrition])
# Compile the model
model.compile(optimizer='adam', loss=['categorical_crossentropy', 'binary_crossentropy'], metrics=['accuracy', 'accuracy'])

# Summarize the model
model.summary()

Model: "functional_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)              ┃ Output Shape           ┃        Param # ┃ Connected to           ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩
│ input_layer_2             │ (None, 10)             │              0 │ -                      │
│ (InputLayer)              │                        │                │                        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_4 (Dense)           │ (None, 64)             │            704 │ input_layer_2[0][0]    │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ dense_5 (Dense)           │ (None, 64)             │          4,160 │ dense_4[0][0]          │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ hidden_layer_department   │ (None, 64)             │          4,160 │ dense_5[0][0]          │
│ (Dense)                   │                        │                │                        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ hidden_layer_attrition    │ (None, 64)             │          4,160 │ dense_5[0][0]          │
│ (Dense)                   │                        │                │                        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ output_layer_department   │ (None, 3)              │            195 │ hidden_layer_departme… │
│ (Dense)                   │                        │                │                        │
├───────────────────────────┼────────────────────────┼────────────────┼────────────────────────┤
│ output_layer_attrition    │ (None, 2)              │            130 │ hidden_layer_attritio… │
│ (Dense)                   │                        │                │                        │
└───────────────────────────┴────────────────────────┴────────────────┴────────────────────────┘

 Total params: 13,509 (52.77 KB)

 Trainable params: 13,509 (52.77 KB)

 Non-trainable params: 0 (0.00 B)

In [49]:
# Train the model
history = model.fit(X_train_scaled, [y_train_department, y_train_attrition], validation_data=(X_test_scaled, [y_test_department, y_test_attrition]), epochs=32, batch_size=50)


Epoch 1/32
23/23 ━━━━━━━━━━━━━━━━━━━━ 4s 19ms/step - loss: 2.4681 - output_layer_attrition_accuracy: 0.6602 - output_layer_department_accuracy: 0.4568 - val_loss: 1.9326 - val_output_layer_attrition_accuracy: 0.8424 - val_output_layer_department_accuracy: 0.7120
Epoch 2/32
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - loss: 1.9754 - output_layer_attrition_accuracy: 0.8307 - output_layer_department_accuracy: 0.6462 - val_loss: 1.7452 - val_output_layer_attrition_accuracy: 0.8424 - val_output_layer_department_accuracy: 0.7120
Epoch 3/32
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.8281 - output_layer_attrition_accuracy: 0.8353 - output_layer_department_accuracy: 0.6394 - val_loss: 1.6624 - val_output_layer_attrition_accuracy: 0.8424 - val_output_layer_department_accuracy: 0.7092
Epoch 4/32
23/23 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.6889 - output_layer_attrition_accuracy: 0.8514 - output_layer_department_accuracy: 0.6378 - val_loss: 1.5807 - val_output_layer_attrition_accuracy: 0.842

In [50]:
# Evaluate the model with the testing data
results = model.evaluate(X_test_scaled, [y_test_department, y_test_attrition])

12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.1433 - output_layer_attrition_accuracy: 0.8618 - output_layer_department_accuracy: 0.7058 


In [51]:
# Print the accuracy for both department and attrition
print(f"Department Accuracy: {results[2]}")
print(f"Attrition Accuracy: {results[1]}")

Department Accuracy: 0.7119565010070801
Attrition Accuracy: 0.8614130616188049


# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

YOUR ANSWERS HERE

1. Is accuracy the best metric to use on this data? Why or why not?
No, accuracy might not be the best metric if the data is imbalanced, like in the attrition task where one class could dominate. The model could predict the majority class more and still seem accurate, even if it’s not performing well on the minority class. Metrics like precision, recall, F1-score, or AUC would give a clearer picture of how well the model handles imbalanced data.

2. What activation functions did you choose for your output layers, and why?
Based on typical usage for a classification problem like this, the softmax activation function was likely used for the department output layer for multi-class classification, and the sigmoid activation function for the attrition output layer for binary classification. Softmax is used to model probabilities over multiple classes, while sigmoid is suited for binary outcomes, providing probabilities between 0 and 1 for the attrition prediction.

    I used L2 regularization to stop the model from overfitting, it helped the model focus on general patterns instead of just memorizing the data. By keeping the weights smaller, L2 helped the model make better predictions on new data and kept things balanced when predicting both department and attrition.

3. Can you name a few ways that this model might be improved?
Several improvements could be made to enhance the model's performance. If the data is imbalanced, techniques like oversampling, undersampling, or using class weights can help the model perform better on the minority class. Adding L2 regularization or dropout could reduce overfitting. Adjusting parameters like learning rate, batch size, or the number of neurons could also improve performance. Creating new features or transforming existing ones can help the model learn better.
